build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

tools:
    external_code_coverage: true

checks:
    php:
        code_rating: true